// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbhovatjpzmtmrmlybqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5iaG92YXRqcHptdG1ybWx5YnFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzNjE2NzIsImV4cCI6MjA0OTkzNzY3Mn0.oZqItarNkNcFz62JbGnW2spZJjwHIYMGAltvRn12h3U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);